[tool.poetry]
name = "workflow-iimi"
version = "0.0.0"
description = ""
authors = ["Ian Boyes"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.12"
virtool-workflow = "^7.1.0"
biopython = "^1.81"
pydantic-factories = "^1.17.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.23.2"
pytest-mock = "^3.12.0"
ruff = "^0.4.8"
syrupy = "^4.6.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff.lint]
select = ["ALL"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
